### ISSUE TITLE
data frame input 

### ISSUE THREAD

**Issue by ciciecho-ds** [UBC-MDS/CryptocurrencyEDA#33]
Can I have sth like this to work with as the output of your function and the input of my function? @berkaybulut 

I see that you have a time frame inputted into your function so I think I will modify mine to just plot whatever is in the data frame. 
![Screen Shot 2022-01-19 at 8 01 00 PM](https://user-images.githubusercontent.com/67261289/150271192-778347f6-11ce-4166-922f-be182591ae6f.png)

**Comment by ciciecho-ds** [comment]
Do you think plotting just the Close price is enough? If so, we can just have the Close column.

**Comment by nobbynguyen** [comment]
@ciciecho-ds : In my function, I also use the closing price only. To simplify our function and package, I think closing price is enough. But if you guys have other ideas like to plot fluctuation during the transaction day, all high, low, close, and open price can be used.

**Comment by ciciecho-ds** [comment]
> @ciciecho-ds : In my function, I also use the closing price only. To simplify our function and package, I think closing price is enough. But if you guys have other ideas like to plot fluctuation during the transaction day, all high, low, close, and open price can be used.

Sounds good. Let's just do close then.

**Comment by berkaybulut** [comment]
Yes, the data output is like this
